services:
  # Flask backend as a web service
  - type: web
    name: assignment4-backend
    runtime: python      # this makes it a Python web service
    branch: main
    rootDir: .           # directory with app.py and requirements.txt
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9

  # React frontend as a static site
  - type: web           # still "web", not "static"
    name: assignment4-frontend
    runtime: static      # indicates this is a static site
    branch: main
    rootDir: frontend    # where package.json and source files live
    buildCommand: npm install && npm run build
    staticPublishPath: dist  # folder to publish after build
    envVars:
      - key: VITE_API_URL
        value: https://assignment4-backend.onrender.com/api
