services:
  - type: web
    name: absenteeism-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: CORS_ORIGINS
        # TEMP: loosen while you bring up the frontend, then replace with the exact frontend URL
        value: "*"
      # If your model file isn't "model.pkl", set it here:
      # - key: MODEL_PATH
      #   value: model.pkl
